[package]
name = "bevy"
version = "0.19.0"
edition = "2024"
publish = false

[lib]
path = "lib.rs"

[dependencies]
bevy_pinned = { package = "bevy", git = "https://github.com/bevyengine/bevy", rev = "7107093556e4069db8399760ba5151b719107c71", default-features = false }

[features]
default = []
bevy_state = ["bevy_pinned/bevy_state"]
